name: "🆕 Sugerir Novo Site"
description: "Sugira a adição de um novo site de anime/mangá/manhua ao nosso catálogo. Forneça informações detalhadas para facilitar a avaliação."
labels: [NovoSite]
body:
  - type: input
    id: site-name
    attributes:
      label: "Nome do Site"
      description: "Digite o nome do site que deseja adicionar."
      placeholder: "Exemplo: SlimeRead ou Mangalivre"
    validations:
      required: true

  - type: input
    id: site-url
    attributes:
      label: "URL do Site"
      description: "Insira o endereço principal do site."
      placeholder: "Exemplo: https://slimeread.com"
    validations:
      required: true

  - type: input
    id: site-language
    attributes:
      label: "Idioma Principal"
      description: "Informe o idioma predominante do site."
      placeholder: "Exemplo: Português"
    validations:
      required: true

  - type: textarea
    id: site-description
    attributes:
      label: "Descrição do Site"
      description: "Dê uma breve explicação sobre o site e o que ele oferece."
      placeholder: "Exemplo: O SlimeRead é uma plataforma com milhares de mangás disponíveis para leitura online gratuita, com suporte para download."
    validations:
      required: true

  - type: textarea
    id: site-features
    attributes:
      label: "Principais Funcionalidades"
      description: "Liste os principais recursos disponíveis no site."
      placeholder: |
        Exemplo:
        - Leitura online de mangás
        - Download de capítulos
        - Suporte para múltiplos idiomas
        - Sistema de favoritos
        - Notificações de novos capítulos
    validations:
      required: true

  - type: textarea
    id: site-popularity
    attributes:
      label: "Popularidade e Relevância"
      description: "Se souber, informe dados sobre a popularidade do site."
      placeholder: "Exemplo: O site recebe mais de 1 milhão de visitas mensais e tem uma comunidade ativa no Discord."

  - type: textarea
    id: additional-info
    attributes:
      label: "Observações Adicionais (Opcional)"
      description: "Caso tenha alguma informação extra, insira aqui."
      placeholder: "Exemplo: O site também possui um aplicativo para Android."

  - type: checkboxes
    id: acknowledgements
    attributes:
      label: "Confirmações"
      description: "Por favor, confirme os seguintes pontos antes de enviar."
      options:
        - label: "Eu verifiquei que este site ainda não está listado no catálogo."
          required: true
        - label: "Forneci todas as informações necessárias sobre o site."
          required: true
        - label: "Confirmo que o site é legítimo e não infringe direitos autorais."
          required: true
        - label: "Estou ciente de que a aprovação da sugestão não é garantida."
          required: true
